spring:
  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.database}
      username: ${mongo.username} 
      password: ${mongo.password}
  mvc:
      view:
        prefix: /html/
        suffix: .html
server:
  port: 19095